<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0WjClY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0WjClY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0WjClY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0WjClY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0WjClY\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0WjClY',
    'container.build_id' => 'eafcd5ea',
    'container.build_time' => 1592403929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0WjClY');
